### ISSUE TITLE
Command "install-modx" is not defined.

### ISSUE THREAD

**Issue by designbywilliam** [modmore/Gitify#46] opened 2015-01-25 18:42 UTC
Running Gitify and choosing to install modx gives me this error:

Command "install-modx" is not defined.
Did you mean this?
install:modx

You probably know this, but thought id just add it here to make sure you add the right command until next update.

**Comment by Mark-H** [comment] 2015-01-25 22:45
Dupe of #42 and should be fixed with https://github.com/modmore/Gitify/commit/bec55cef6dcfaf4f0f9b9550e280e1627049acec

**Closed by Mark-H** 2015-01-25 22:45 UTC
