### ISSUE TITLE
Support for Directories with spaces or configuration check

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/Gitify#181] opened 2016-02-24 08:13 UTC
### Summary
Using Gitify to start a fresh project in a directory structure like this:
`F:/Work/Workspace/Client - Project/`

### Step to reproduce
Create a folder with a space in it and try to run: 
`Gitify modx:install`

### Observed behavior
After successfully downloading, extracting and configuring MODX through the CLI, it breaks:
```
Running MODX Setup...
Could not open input file: F:/Work/Workspace/Client
```

### Expected behavior
Either it should just work, or it should instruct me to use a directory without spaces.
But actually it should just work :smile: And if it won't work, 
then this case could/should be checked beforehand. 

### Environment
- Gitify 0.12.0
- Windows 10

**Comment by Mark-H** [comment] 2016-04-13 16:53
Duplicate of #145

**Closed by Mark-H** 2016-04-13 16:53 UTC
Labels: bug
